<a href="https://colab.research.google.com/github/pandharkardeep/Compute_tasks_Deep_P/blob/main/Copy_of_Task_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import NumPy

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
c = np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
d = np.arange(10,51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
e = np.arange(10,51,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
f = np.arange(0,9).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
h = np.random.random()
h

0.8481702361445528

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
i = np.random.randn(25)
i

array([-0.0126338 , -1.15449789,  0.62583985,  0.92710907,  0.73090538,
        0.79204099,  1.60717114,  0.16494439, -0.3142027 , -1.90467371,
        0.90722857, -0.10025576, -0.02510202,  0.38621642, -1.43813129,
       -0.39314459, -0.25384558,  1.41342252,  0.06038357, -0.47786067,
        0.89257162,  0.06858729, -0.83809832,  0.5587252 , -0.12368786])

#### Create the following matrix: -!del!-

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
j = np.linspace(0,1,20)
j

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
submat = mat[2:,1:]
submat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
num = mat[-2,-1]
num

20

20

In [ ]:
submat2 = mat[:3,1].transpose()
submat2.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
submat3 = mat[-1,:]
submat3

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
submat4 = mat[-2:-1,:]
submat4

array([[16, 17, 18, 19, 20]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = [[1,2],[2,3]]
B = [[4,5],[6,7]]
np.multiply(A,B)

array([[ 4, 10],
       [12, 21]])

####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
A= [[ 1.3, 2.5, 3.6, np.nan], [ 2.6, 3.3, np.nan, 5.5], [ 2.1, 3.2, 5.4, 6.5]]
res = np.where(np.isnan(A), np.ma.array(A,
               mask = np.isnan(A)).mean(axis = 0),A)
res

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

# You're done!